### ISSUE TITLE
Implement a `run` command for Iridium

### ISSUE THREAD

**Issue by joshfischer1108** [IridiumIdentity/iridium#127]
**Is your feature request related to a problem? Please describe.**
Just like we have an `init` command, we need a `run` or a `start` or similar command to execute from the Iridium CLI to ease the process of managing properties, and etc. 

**Describe the solution you'd like**
I'd like a run command implemented in the Iridium CLI.  `iridium run ....args`.  It doesn't have to be exactly like this, it's only an idea at this point.  The CLI should reference the application.properties file int the `conf` folder of the distribution. 

**Describe alternatives you've considered**
We can already run the jar as `java -jar ....`, it would be better if we bundled the run command in with the project for a common interface. 

**Additional context**

**Comment by Durdush** [comment]
Hi @joshfischer1108, I want to work on this. Could you please assign me this? Also will need some help to understand the exact requirement.

**Comment by joshfischer1108** [comment]
Hi @Durdush , we would appreciate the help, thank you!

 The command would need to be added to the [iridum-cli module](https://github.com/IridiumIdentity/iridium/tree/main/iridium-cli).

I would start with getting a little familiar with how this module is setup, the tar.gz file it generates.  I'll have some time later today to write more requirements.

**Comment by joshfischer1108** [comment]
Ok.  Here are some terse instructions to get you going. I'll add more details as you go.  Assuming you are on OSX and in the root folder of the project.
1. To to use the cli
```
#build the project
$ mvn clean install 
# untar the cli
$  tar -xzf iridium-cli/target/iridium-0.2.2-SNAPSHOT-bin.tar.gz 
```
The untarred folder will have the structure as below. 
```
# cd into distro folder
$ cd iridium-0.2.2-SNAPSHOT-bin/
# run tree to see the folders
$ tree
.
├── LICENSE
├── README.md
├── bin
│   ├── iridium
│   └── iridium.bat
├── bootIridium.sh
├── conf
│   ├── application-types.yaml
│   ├── application.properties <- this is the properties file you need to reference. 

```
under the `conf` folder is an application.properties file you'll need when you execute the `iridium-core-server-0.2.2-SNAPSHOT.jar` under the `lib` folder.   

To run the project you could do something like 
```
java -jar iridium-core-server-0.2.2-SNAPSHOT.jar --spring.config.location=file:///Users/home/config/applicadtion.properties
```

The run command implementation can start [in this file if you wish](https://github.com/IridiumIdentity/iridium/blob/main/iridium-cli/src/main/java/software/iridium/cli/command/RunCommand.java)

**Comment by Durdush** [comment]
Thanks for assigning and steps to start up.

**Comment by Durdush** [comment]
Hi @joshfischer1108, i am stuck in some personal emergency So i could not inform you earlier. Sorry!!  also  I will not able to work on this in upcoming week, if that affects your timeline for this issue then Please assign this to some one else.

**Comment by joshfischer1108** [comment]
@Durdush Most importantly, I hope everything is ok.   

If you still want to work on it, it's yours.  If you need some time before you can come back to it, this is fine too, just let me know.

**Comment by Durdush** [comment]
Thank you very much @joshfischer1108. I am looking into this now.

**Comment by joshfischer1108** [comment]
Glad you are back, hope all is well. Looking forward to your solution 😄

**Comment by joshfischer1108** [comment]
@Durdush , did you ever get a chance to start on this?
