### ISSUE TITLE
Add documentation on how to run iridium locally

### ISSUE THREAD

**Issue by joshfischer1108** [IridiumIdentity/iridium#130]
**Is your feature request related to a problem? Please describe.**
As a developer, I want to be able to run Iridium from an IDE to test the changes I am making. 

**Describe the solution you'd like**
A doc describing how to run iridium.

**Describe alternatives you've considered**

**Additional context**

**Comment by Horicabu** [comment]
Hello, I'd enjoy contributing to this issue, is it still open?

**Comment by joshfischer1108** [comment]
It is and we would appreciate the help!  If you are willing I'll get you assigned to the story and answer any questions you need. 

Let me know!

**Comment by Horicabu** [comment]
sure, add me in.

**Comment by joshfischer1108** [comment]
We have some docs written for Intellij, it'd be nice to get support for the other IDEs if you have knowledge of them.  

Either way, the docs I have for Intellij aren't really doing the job, because people often have questions on how to run the API.  Let me know what you need from me and I'll do what I can to help.  

Thank you!

**Comment by Horicabu** [comment]
Note: In order to run Iridium, you need to build from source.

**Comment by joshfischer1108** [comment]
@Horicabu , how are things going?  Anything I can do to help?

**Comment by Horicabu** [comment]
I'm currently writing the docs! Expect something today

**Comment by joshfischer1108** [comment]
@Horicabu , we got this done already, right?

**Comment by Horicabu** [comment]
I believe this is resolved for the current Iridium iteration, yes.
