### ISSUE TITLE
Restrict Token Refresh to Confidential Clients only 

### ISSUE THREAD

**Issue by joshfischer1108** [IridiumIdentity/iridium#138]
**Is your feature request related to a problem? Please describe.**
To enhance security we need to restrict the token refresh grant to confidential clients only.

**Describe the solution you'd like**
I think we should modify the current endpoint to restrict it to confidential clients only.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by joshfischer1108** [comment]
@erzohrakhan are you interested in working on this issue?

**Comment by erzohrakhan** [comment]
@joshfischer1108 Yes I am interested; but how should we restrict it to confidential clients only

**Comment by crucio-009** [comment]
@joshfischer1108 if I get it right, to restrict it to confidential clients we can introduce a field representing the client type on registering clients. I will send a more detailed approach over email. Hope to hear from you!

**Comment by erzohrakhan** [comment]
We need to check whether the client is authorised or not through servlet request; If the client is authorised then only a refresh token will be generated. Working with PR
