### ISSUE TITLE
Add Microsoft as an external identity provider

### ISSUE THREAD

**Issue by joshfischer1108** [IridiumIdentity/iridium#148]
**Is your feature request related to a problem? Please describe.**
As an admin of Iridium, I'd like to be able to allow my customer base to log into my system with their Microsoft account. 

**Describe the solution you'd like**
I need to be able to add Microsoft via a no-code interface like we do with GitHub and Google

**Describe alternatives you've considered**
n/a
**Additional context**
n/a

**Comment by joshfischer1108** [comment]
These are the Microsoft docs to cover the authorization code flow. 

https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow

**Comment by Harshal662** [comment]
I can try that.

**Comment by joshfischer1108** [comment]
@Harshal662 I'll add a few more details to the story to hopefully get you the detail needed to get this done. Give me until the end of the day to get them to you.

**Comment by joshfischer1108** [comment]
After I get them added, the issue is all yours, if you still want it.

**Comment by joshfischer1108** [comment]
@Harshal662 I was not able to get the details written out for you. I apologize,  Will get it done tomorrow.

**Comment by Harshal662** [comment]
@joshfischer1108 Chill, Its okay.

**Comment by joshfischer1108** [comment]
First, we will need to add the appropriate details for the Microsoft OAuth endpoints.  You can add them to this [file here](https://github.com/IridiumIdentity/iridium/blob/main/conf/external-provider-templates.yaml).   

The code that then performs the exchange based on the YAML files is [here](https://github.com/IridiumIdentity/iridium/blob/39f4c2e989428d722ed17c91db0d81cc443cf93b/iridium-core-server/src/main/java/software/iridium/api/service/AuthorizationService.java#L94)

You won't change the conf files in the repo, but in the release distribution. You can read more about it [here](https://docs.iridium.software/0.2.1/3.-Running-Locally/1.Install-the-CLI/)

After you have the CLI ready you can [stand up locally](https://docs.iridium.software/0.2.1/3.-Running-Locally/2.run-iridium-locally/).  

I'll stop here for now, let me know what questions you have, I'll try to help the best I can 😄
