### ISSUE TITLE
Add refresh token API end point to document and update .gitignore 

### ISSUE THREAD

**Issue by erzohrakhan** [IridiumIdentity/iridium#159]
**Is your feature request related to a problem? Please describe.**
I'm suggesting two improvements:

Add documentation for the refresh token endpoint.
Update the `.gitignore `file to prevent unnecessary files from the `.idea` folder from being uploaded to version control.
**Describe the solution you'd like**

Document the refresh token endpoint to provide better guidance.
Modify the .`gitignore` file to exclude all files within the `.idea` folder, as these files are specific to the IntelliJ IDEA IDE and should not be included in version control.

**Comment by joshfischer1108** [comment]
Thanks for reporting this, @erzohrakhan.  I have it assigned to you!
