### ISSUE TITLE
How can we store applications and related configuration as infrastructure as code?

### ISSUE THREAD

**Issue by joshfischer1108** [IridiumIdentity/iridium#162]
**Is your feature request related to a problem? Please describe.**
As a developer, I'd like a way to manage my applications per environment in a manner that will help with Disaster Recovery.

**Describe the solution you'd like**
I'd like a diagram to show ways we can manage applications in Iridium.  It could be via YAML, JSON, etc. Is there a better way? 

At this point, we are only ideating.  No implementation is necessary.

**Describe alternatives you've considered**
At this time the applications are managed via the admin-ui

**Additional context**

**Comment by joshfischer1108** [comment]
@rwithers , I could use some ideating on this issue.  What do you think?

**Comment by OshaibBeg** [comment]
Hey @joshfischer1108 I want to take that issue.
