### ISSUE TITLE
Enhance Contributing.md

### ISSUE THREAD

**Issue by joshfischer1108** [IridiumIdentity/iridium#163]
**Is your feature request related to a problem? Please describe.**
The [Contributing.md](https://github.com/IridiumIdentity/iridium/blob/main/CONTRIBUTING.md) file in the repo isn't clear on how others can contribute to Iridium. 

**Describe the solution you'd like**
I'd like to enhance the doc to include what a person should do to start working on Iridium.  

E.g.
- Propose an issue to be fixed OR select an already existing one
- Fork the repository 
- Create a branch with the naming convention {name}/issue-{issueNumber}-short-description of the issue. 

**Describe alternatives you've considered**
The example above is not how it needs to be, only a not so well thought out suggestion.

**Additional context**
Many developers have been unsure how to start working on Iridium, this issue is meant to address the problem.

**Comment by joshfischer1108** [comment]
@crucio-009 ,  you interested in working on this?

**Comment by rwithers** [comment]
I think the lead in to this has to make "contributing" as approachable as possible.  I have some ideas about how to do this and I'm open to working with others on it. I'll make the first draft tomorrow afternoon and then commit that draft for others to review.

**Comment by joshfischer1108** [comment]
@rwithers  I think it would be good to work with @crucio-009 to get your ideas added to him.  He started work on this PR, we just haven't assigned the issue yet.  cc @crucio-009 

Thoughts?

**Comment by crucio-009** [comment]
I have updated the contributing doc in accordance to our discussion @joshfischer1108 in #169

**Comment by joshfischer1108** [comment]
Hi @crucio-009 , are you still working on this issue?

**Comment by crucio-009** [comment]
Sorry @joshfischer1108 can't take this up now. Busy with something else.

**Comment by joshfischer1108** [comment]
@crucio-009 , no worries. Thanks for letting me know!

**Comment by MihirKohli** [comment]
Can you assign this issue to me?

**Comment by rwithers** [comment]
Done. I would like to discuss some ideas I have with you @MihirKohli

**Comment by joshfischer1108** [comment]
Thanks for jumping on this @MihirKohli , let me know what you need to help get it done.
