### ISSUE TITLE
Documentation `NEXT` version deployment issue

### ISSUE THREAD

**Issue by joshfischer1108** [IridiumIdentity/iridium#165]
**Describe the bug**
We have a GitHub workflow that runs on every commit to `main` that updates the `NEXT` version of the docs.  This workflow is publishing the `NEXT` version incorrectly.  

**To Reproduce**
1. Go to https://docs.iridium.software/NEXT/
2. See that the side navigation menu is missing.
<img width="1425" alt="Screenshot 2023-09-11 at 8 00 36 PM" src="https://github.com/IridiumIdentity/iridium/assets/5785700/00eb0b6d-d353-485e-aec3-a7a7a581c341">

**Expected behavior**
Side navigation should appear like on version `0.2.1`
<img width="1385" alt="Screenshot 2023-09-11 at 8 00 44 PM" src="https://github.com/IridiumIdentity/iridium/assets/5785700/f64af2de-c2ab-41df-855c-93e677cf5a75">

**Screenshots**
Above

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by Nkiriobasi** [comment]
Please can I make a PR

**Comment by joshfischer1108** [comment]
Hi Nkiri,

I saw a comment come through.  I'd appreciate the help if you are still
willing to help. If so, let me know and I'll get you assigned to the issue.

**Comment by Nkiriobasi** [comment]
Yes, I'm still willing to help.
