### ISSUE TITLE
Add Java client for Iridium

### ISSUE THREAD

**Issue by joshfischer1108** [IridiumIdentity/iridium#168]
**Is your feature request related to a problem? Please describe.**
As a developer, I'd like to be able to use Iridium with Java for frameworks like [The Spring framework](https://spring.io/projects/spring-framework), but not limited to.

**Describe the solution you'd like**
We should add a client module with the project under the name `iridium-client-java`.    That uses a [client credentials grant](https://datatracker.ietf.org/doc/html/rfc6749#section-4.4).  It should be noted that there is there is an existing Maven module called `iridium-java-client` that we could rename and use to house this code. 

The client should be able to be configured with a  few parameters to run
* `clientId`
* `clientSecret`
* `domain`

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by erzohrakhan** [comment]
@joshfischer1108 I would like to work on this issue

**Comment by joshfischer1108** [comment]
Fantastic, @erzohrakhan , I'm looking forward to your solution.

**Comment by joshfischer1108** [comment]
Hi @erzohrakhan , how's it going?  Have you had a chance to work on this issue?

**Comment by OshaibBeg** [comment]
Hey @joshfischer1108 are there any active contributor for this issue? If not, Please assign it to me.

**Comment by erzohrakhan** [comment]
@OshaibBeg Yes u can work on this

**Comment by OshaibBeg** [comment]
Thank you for the response, Actually I am naive here can you please tell me all the prerequisite for this issue.
Your help are very much appreciated.
