### ISSUE TITLE
Add lombok to Iridium

### ISSUE THREAD

**Issue by joshfischer1108** [IridiumIdentity/iridium#173]
**Is your feature request related to a problem? Please describe.**
We'd like to use a way to generate getters/setters and builder functions. 

**Describe the solution you'd like**
I'd like to use [Lombok](https://projectlombok.org/) 

**Describe alternatives you've considered**

n/a

**Additional context**
n/a

**Comment by haseeb-xd** [comment]
Hello @joshfischer1108 ,
 I want to take this up. Do I only have to add Lombok dependency?

**Comment by joshfischer1108** [comment]
Thanks for your interest @haseeb-xd.  This is active work already assigned to someone, I just haven't had the chance to assign the work to him. 

We have plenty of other issues to work through if you are interested.  If you see them with the `active-work` label, this means someone is already working on it. Other than that, feel free to look around. I'm happy to answer any questions along the way.

**Comment by zhajikun** [comment]
JakeChrysler will take this task of adding Lombok.
