### ISSUE TITLE
Create a Doc that describes the Architecture

### ISSUE THREAD

**Issue by dave2wave** [IridiumIdentity/iridium#18]
**Is your feature request related to a problem? Please describe.**
Understanding what Irudium is all about.

**Describe the solution you'd like**
A simple architecture diagram and table or list of the software components would help newcomers like me understand what's going on.

**Describe alternatives you've considered**
I could hack around, but I suspect that it would be quickly frustrating.

**Comment by joshfischer1108** [comment]
This is a fantastic ask, @dave2wave .  I'll get something put together in the next few days.

**Comment by joshfischer1108** [comment]
@dave2wave I'm still in progress, but I merged [this](#19 ) a few minutes ago for some initial feedback.   More updates soon to come. 

Docs can be found at
https://docs.iridium.software/

**Comment by dave2wave** [comment]
That's a good start.

**Comment by joshfischer1108** [comment]
@dave2wave I made a few more tweaks.  Does this [page](https://docs.iridium.software/1.-overview/overview/) fulfill what you were thinking about on this ticket? 

I wouldn't say the overview page is done by any means, we still have a long way to go.
