### ISSUE TITLE
[BUG]: User is not able to logout from the site.

### ISSUE THREAD

**Issue by Brijesh206** [IridiumIdentity/iridium#204]
**Describe the bug**
User is not able to logout after login to the site.

**To Reproduce**
1. Go to 'https://conduct.iridium.software/'
2. Click on 'Sign In or Register'
3. After Sign In, click on hamburger icon and try to logout
4. You will not able to logout

**Expected behavior**
When user click on logout, user will logout from the site and redirected to the Sign In/ Register/ Home page.

**Screenshots**
![image](https://github.com/IridiumIdentity/iridium/assets/92438772/ac6792d8-4ce3-4c9f-bc08-a8396b437c90)

**Desktop:**
 - OS: Windows 10 Home
 - Browser: Brave ( Version : 1.58.131 )

**Comment by joshfischer1108** [comment]
Fixed with https://github.com/IridiumIdentity/iridium-ui/commit/28d416201fdb7fedae103664c2a9778332eec434
