### ISSUE TITLE
Duplicate word in readme file

### ISSUE THREAD

**Issue by Brijesh206** [IridiumIdentity/iridium#205]
**Describe the bug**
There is a duplicate word "the" in README.md file.

**Screenshots**
![image](https://github.com/IridiumIdentity/iridium/assets/92438772/e64b170d-90cb-4f2c-9da8-233d7be24cb6)

**Comment by Brijesh206** [comment]
I would like to work on this as my first open source contribution.

**Comment by joshfischer1108** [comment]
@Brijesh206 , we would love to have you work on the project.  Please open a PR for the fix.
