### ISSUE TITLE
Exceptions thrown in filters result in 500's by default 

### ISSUE THREAD

**Issue by joshfischer1108** [IridiumIdentity/iridium#209]
**Describe the bug**
Whenever an exception is thrown in a filter, in results in a  500.  

As an example, if you try to use an API with an invalid token, the filter will throw a `NotAuthorized` exception, which should result in a 4xx error.  Instead, a 500 is thrown.

**To Reproduce**
1. Get a valid token by logging into the admin UI, locally. 
2. Simlate an identity API call, such as
```
curl --location --request GET 'localhost:8381/identities' \
--header 'Accept: application/vnd.iridium.id.identity-response.1+json' \
--header 'Authorization: Bearer $2a$10$xyi4epfHmUrTnXwB/zIQo.X2dHCHHtkGTjnPmOKHXb/mw9QwKkkDq' \
--header 'Content-Type: application/json' 
```

**Expected behavior**

A 401 error should be thrown

**Comment by sivasuriyankumarasamy** [comment]
Hi @joshfischer1108,

I can try to fix this issue. Can you assign this to me?

Also is there any DB config that i need to do to run this app in my local?

**Comment by Brijesh206** [comment]
Hey @joshfischer1108 
I would like to work on this issue.

**Comment by joshfischer1108** [comment]
> Hi @joshfischer1108,
> 
> I can try to fix this issue. Can you assign this to me?
> 
> Also is there any DB config that I need to do to run this app in my local?

Yes, I would follow the [getting started locally docs](https://docs.iridium.software/0.2.2/3.-Running-Locally/1.Install-the-CLI/)

I'll get this assigned to you, let me know if you are still interested @sivasuriyankumarasamy

**Comment by joshfischer1108** [comment]
> Hey @joshfischer1108 I would like to work on this issue.

@Brijesh206 , let's wait to hear back from @sivasuriyankumarasamy first.

**Comment by Brijesh206** [comment]
Okay

**Comment by sivasuriyankumarasamy** [comment]
> > Hi @joshfischer1108,
> > I can try to fix this issue. Can you assign this to me?
> > Also is there any DB config that I need to do to run this app in my local?
> 
> Yes, I would follow the [getting started locally docs](https://docs.iridium.software/0.2.2/3.-Running-Locally/1.Install-the-CLI/)
> 
> I'll get this assigned to you, let me know if you are still interested @sivasuriyankumarasamy

Yeah. I would like to work on this. can you asign this to me?

**Comment by joshfischer1108** [comment]
> > > Hi @joshfischer1108,
> > > I can try to fix this issue. Can you assign this to me?
> > > Also is there any DB config that I need to do to run this app in my local?
> > 
> > 
> > Yes, I would follow the [getting started locally docs](https://docs.iridium.software/0.2.2/3.-Running-Locally/1.Install-the-CLI/)
> > I'll get this assigned to you, let me know if you are still interested @sivasuriyankumarasamy
> 
> Yeah. I would like to work on this. can you asign this to me?

Absolutely.  How can I help you get started?

**Comment by sivasuriyankumarasamy** [comment]
> > > > Hi @joshfischer1108,
> > > > I can try to fix this issue. Can you assign this to me?
> > > > Also is there any DB config that I need to do to run this app in my local?
> > > 
> > > 
> > > Yes, I would follow the [getting started locally docs](https://docs.iridium.software/0.2.2/3.-Running-Locally/1.Install-the-CLI/)
> > > I'll get this assigned to you, let me know if you are still interested @sivasuriyankumarasamy
> > 
> > 
> > Yeah. I would like to work on this. can you asign this to me?
> 
> Absolutely. How can I help you get started?

I am able to return 401. with out any body.

Is it fine? or it should go through controller advice and return the model?
