### ISSUE TITLE
Refactoring Request: Move Code for Finding Application by clientId.

### ISSUE THREAD

**Issue by erzohrakhan** [IridiumIdentity/iridium#219]
**Describe the bug**
Currently, in the `AuthorizationService.java`, there's code for finding an application by `clientId`. This code is repeated in multiple places and can be refactored for better code readability and reusability.

**Proposed Refactoring:**
Move the code for finding an application by `clientId` to the `ApplicationService.java` class, encapsulating it in a dedicated method called `findByClientId`. This will improve code organization and allow for easier reuse.

**Code Snippets:**
**ApplicationService.java:**
```java
@Service
public class ApplicationService {

    public Application findByClientId(String clientId) {
        
    }
    
}

final var application =
        applicationRepository
            .findByClientId(clientId)
            .orElseThrow(
                () ->
                    new ResourceNotFoundException(
                        "application not found for clientId: " + clientId));
can be rewritten as 
    final var application = applicationService.findApplicationByClientId(clientId);
```
This refactoring will enhance the maintainability and readability of our codebase.

**Acceptance Criteria:**

The code has been successfully refactored as described.
Tests have been updated to ensure that the refactored code works as expected.

**Comment by erzohrakhan** [comment]
@Brijesh206 Do you want to work on this issue?

**Comment by Brijesh206** [comment]
@erzohrakhan Yes I want to work on this issue.

**Comment by erzohrakhan** [comment]
@joshfischer1108 
Yes, I agree that these changes do not add any feature/functionality and this will require thorough testing
but Authorizationservice.java is very hard to read especially the exchange function, and maintaining this code will be cumbersome(when the project grows)
At a few places with functional programming, we can decrease the number of LOC

So I thought to do it now when we don't have any customers
