### ISSUE TITLE
Documentation Update for Iridium Overview

### ISSUE THREAD

**Issue by Horicabu** [IridiumIdentity/iridium#225]
**Is your feature request related to a problem? Please describe.**
I'm in process of revamping and adding onto Iridium's documentation.

**Describe the solution you'd like**
I've created an update for the overview doc beforehand.
Next I will make documentation for the database and API.

**Describe alternatives you've considered**
None required.

**Additional context**
I will comment here as I complete documents to record the changes publically.

**Comment by Horicabu** [comment]
The revamp of the original Overview document is done.
Next I will make a document for the database.

**Comment by joshfischer1108** [comment]
Should we close this, @Horicabu ?

**Comment by Horicabu** [comment]
@joshfischer1108 I am still at work on the next document. Progress has been slow due to circumstances out of my control, but this issue is still being worked on.

**Comment by Horicabu** [comment]
We have decided to make the next set of documents have their own category. Because the revised intro doc itself is finished, this issue is resolved.
