### ISSUE TITLE
Add ability to lint `iridium-angular-client`

### ISSUE THREAD

**Issue by joshfischer1108** [IridiumIdentity/iridium#77]
**Is your feature request related to a problem? Please describe.**
Currently the `iridium-angular-client` is a bit messy in terms of code format consistency.  I'd like a way to lint or enforce a code format within this module.

**Describe the solution you'd like**
I'd like to use a tool like [ng lint](https://angular.io/cli/lint) to help with this task.  As a developer, I could run a command like `ng lint` to format my code to a specific format. If we could do this, we could use code formatting as part of a pre-check for quality in PRs as well. 

**Describe alternatives you've considered**
I have not.  I'm open to using any tool that will get the job done well. 

**Additional context**
n/a

**Comment by joshfischer1108** [comment]
@timgrein, This one would be good to work on, if you are interested.

**Comment by timgrein** [comment]
Can take a look 👍
