### ISSUE TITLE
Document how to revoke access from an authorized GitHub application

### ISSUE THREAD

**Issue by joshfischer1108** [IridiumIdentity/iridium#91]
**Is your feature request related to a problem? Please describe.**
When testing how to use Iridium for my applications it would be nice to know how to revoke access of an application I authorized that is registered in Github.  This is helpful as I'll be able to visualize all the steps of a customer working through my authorization flow. 

**Describe the solution you'd like**
A set of documentation describing how to revoke access to a GitHub application. 

**Describe alternatives you've considered**
n/a

**Additional context**

**Comment by sistla-gautam** [comment]
Hey, I just came across this issue. I would like to ask a doubt regarding the issue.

Is the issue stating that there is documentation required to revoke access to a Github application. If this is the case, it can be done via GitHub.
GitHub themselves provided a documentation on the same [here.](https://docs.github.com/en/apps/using-github-apps/reviewing-and-revoking-authorization-of-github-apps)

If this does seem like the right thing, I can help in the documentation process if possible.

Thank you

**Comment by joshfischer1108** [comment]
@sistla-gautam Thank you for your comment.  I think you bring up a great point and it's something I've been on the fence about for some time now. 

I'd like for Iridium to have a comprehensive set of documentation with the hope that people can get all their questions answered within the Iridium docs, but I know this also isn't completely possible. I also feel the pain when I go to one page and get redirected to a new site entirely for the answer. E..g going from https://docs.iridium.software -> https://docs.github.com/.  

Also, in other parts of the docs, people would need to enter specific values for the management UI to work.   E.g. [This link here](https://docs.iridium.software/0.2.1/5.-External-Identity-Providers/create-github-application/).  

So I'm a bit on the fence about the best way to provide this information, I think you may have a good idea of just organizing links to external pages as we have plenty more to add than just GitHub or Google.  

What do you think?  How would you do it?  I'm open to whatever you think could be better.

**Comment by sistla-gautam** [comment]
Hey @joshfischer1108 ,

I think we can include this as a link which redirects to external sites as a way of providing immediate and emergency help to others.

In the meanwhile, we can streamline the documentation into a single cohesive place where all the documentation resides without any much (if not any) redirects to external sites.

Let me know how I can help.

PS: This is first time trying to contribute to opensource. Please forgive me for any mistakes and etiquette that I might have missed.

Thank you

**Comment by joshfischer1108** [comment]
@sistla-gautam It sounds like you have a good idea of how you can make the docs better. I'd love to see what you come up with.  I'm happy to help and answer any questions you have along the way.  

What do you think?  I'll get you assigned to this issue if you are willing to give it a try!

**Comment by sistla-gautam** [comment]
@joshfischer1108 sure. I'll try my best to help as much as I can. Please do assign this to me and I'll try my very best.

**Comment by joshfischer1108** [comment]
Thank you! I'll get it assigned.  Let me know if you have any questions or need any help along the way!

Sorry for my delay.

**Comment by joshfischer1108** [comment]
Hi @sistla-gautam , are you still working on this?

**Comment by sistla-gautam** [comment]
Hey, I have already submitted the PRs ,and it got merged too. Do you want me to still work on something on this?
