### ISSUE TITLE
I'd like to stand up Iridium locally with a "1 button click"

### ISSUE THREAD

**Issue by joshfischer1108** [IridiumIdentity/iridium#92]
**Is your feature request related to a problem? Please describe.**
// todo @joshfischer1108 

**Describe the solution you'd like**
The way I currently understand this problem is one of complexity.  You have many different options for starting, running, and configuring iridium and all of them require a number of steps.  Building a "1-click" solution is about eliminating these options so that future users / developers can get started using iridium quickly and easily. 

**Describe alternatives you've considered**

**Additional context**

**Comment by rwithers** [comment]
@joshfischer1108 if you want to work on this one please let us know.
